import os
from dotenv import load_dotenv
from typing import TypedDict, Annotated, Sequence

from langchain_groq import ChatGroq
from langgraph.graph import StateGraph, START, END
from langgraph.prebuilt import ToolNode
from langchain_core.messages import HumanMessage, BaseMessage, SystemMessage, AIMessage
from langgraph.graph.message import add_messages


from doc_tools import *
from utils import get_sample_prompt_response

load_dotenv()
API_KEY = os.getenv("GROQ_API_KEY")

llm = ChatGroq(
    model = "llama-3.1-8b-instant",
    api_key = API_KEY,
    temperature = 0
)

tools_list = [write_markdown, read_markdown,
              write_paragraph, write_header, write_sub_header, write_bullet_points,write_ordered_list, save_doc, invoke_rag]
llm = llm.bind_tools(tools_list)


class AgentState(TypedDict):
    messages: Annotated[
        Sequence[BaseMessage], add_messages
    ]

def create_todo(state: AgentState) -> AgentState:
    example_prompt, example_response = get_sample_prompt_response()
    sys_msg = SystemMessage(content = f"""
        You are a helpful assistant!
        You are supposed to create a todo plan for another LLM agent to follow and create a word doc based on the user prompt.
        You and the other agent will receive the same user prompt

        You have one tool: write_markdown
        Never call any other tool

        example prompt: {example_prompt}
        example response: {example_response}

        Do not search the web for any data, just answer with your knowledge.
        Do not write the content for the word doc. Just refer the example prompt-response pair
    """)
    response = llm.invoke(
        [sys_msg] + state["messages"]
    )
    print("TODO created!")
    return dict(
        messages = [response]
    )

def generate_doc(state: AgentState) -> AgentState:
    """
    Generates content and calls tools to write content in the doc
    :param state: AgentState
    :return: AgentState
    """
    sys_msg = SystemMessage(content="""
        You are a helpful assistant!
        You are supposed to build a word document by reading instructions generated by another LLM agent.
        You and the other agent will receive the same user prompt

        You have these tools: 
            read_markdown: call this tool to read the instructions
            write_paragraph: write only paragraph to the document
            write_header: add a header in the document
            write_sub_header: adds a sub header (use this for the sub sections)
            write_bullet_points: add bullet points in the document
            write_ordered_list: add order points in the document
            invoke_rag: if the user has uploaded a PDF file then call this tool and retrieve the context
            save_doc: save the doc (Give the file a name. Every new file gets a new name. Valid file ext: .docx)
        Never call any other tool.
        Read the instructions, generate content and call the appropriate tool
        You will be given the header, sub-headers and then the instructions to generate the content for the sub-headers.

        Do not search the web for any data, just answer with your knowledge.

        You are expected to create a word doc
    """)
    response = llm.invoke(
        [sys_msg] + state["messages"]
    )
    # print(response.tool_calls)
    return dict(
        messages=[response]
    )

def should_continue(state: AgentState) -> str:
    messages = state["messages"][-1]
    if isinstance(messages, AIMessage) and messages.tool_calls:
        return "tool_node"
    return "stop"

def should_rag(state: AgentState) -> str:
    messages = state["messages"][-1]
    if isinstance(messages, AIMessage) and messages.tool_calls:
        return "RAG"
    return "skip"

graph = StateGraph(AgentState)

graph.add_node("create_todo", create_todo)
graph.add_node("generate_doc", generate_doc)
tool_node = ToolNode(tools = tools_list)
graph.add_node("tool_node", tool_node)

graph.add_edge(START, "create_todo")
graph.add_edge("create_todo", "tool_node")
graph.add_edge("tool_node","generate_doc")
graph.add_conditional_edges("generate_doc",
                            should_continue,
                            {
                                "tool_node": "tool_node",
                                "stop": END
                            })
graph.add_edge("tool_node", "generate_doc")

agent = graph.compile()