from typing import Union, List, Annotated, Sequence, TypedDict, Tuple
from dotenv import load_dotenv
import os

from langchain_groq import ChatGroq
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage, BaseMessage, SystemMessage, AIMessage
from langgraph.graph.message import add_messages
from langgraph.graph import StateGraph, START, END
from langgraph.prebuilt import ToolNode

from docx import Document # python word generator

load_dotenv()
API_KEY = os.getenv("GROQ_API_KEY")

llm = ChatGroq(
    model = "llama-3.3-70b-versatile",
    api_key = API_KEY,
    temperature = 0
)

GLOBAL_DOC = Document()
DOC_PATH = os.path.join("generated","demo.docx")

@tool
def write_content(content: str) -> str:
    """
    Write LLM generated content in a word doc
    :param content:  LLM generated content
    :return: confirmation
    """
    doc = Document()

    doc.add_paragraph(content)

    doc.save(DOC_PATH)

    return "word file generated"

@tool
def write_paragraph(para: str) -> str:
    """
    writes paragraph in the doc
    :param para: paragraph
    :return: confirmation
    """
    global GLOBAL_DOC
    GLOBAL_DOC.add_paragraph(para)
    return "paragraph added!"

@tool
def write_bullet_points(points: List[str]) -> str:
    """
    writes bullet points in the doc
    :param points: bullet points
    :return: confirmation
    """
    global GLOBAL_DOC
    for p in points:
        GLOBAL_DOC.add_paragraph(p, style = "List Bullet")
    return "bullet points added!"

@tool
def write_ordered_list(points: List[str]) -> str:
    """
    writes ordered list in the doc
    :param points: ordered list
    :return: confirmation
    """
    global GLOBAL_DOC
    for p in points:
        GLOBAL_DOC.add_paragraph(p, style="List Number")
    return "bullet points added!"

@tool
def write_table(table: List[Tuple]) -> str:
    """
    writes table in the doc
    Important: First tuple MUST be the header names
    :param points: table
    :return: confirmation
    """
    global GLOBAL_DOC

    rows = len(table); cols = len(table[0]) # assuming that all rows have the same number of column
    table = GLOBAL_DOC.add_table(rows = rows, cols = cols)

    if rows == 0:
        return "Empty table"

    header = table[0]
    for idx, h in enumerate(header):
        table.rows[idx].text = h

    data = table[1:]
    for row_idx, row in enumerate(data, 1):
        for col_idx, col_text in enumerate(row):
            table.rows[row_idx].text = col_text

    return "table created!"


@tool
def save_doc() -> str:
    """
    Saves the document
    :return: confirmation
    """
    global GLOBAL_DOC
    GLOBAL_DOC.save(DOC_PATH)
    return "Doc saved!"

@tool
def read_markdown() -> str:
    """
    Read instructions from a markdown file
    :return: instructions
    """
    with open("TODO.md", "r") as md:
        content = md.read()
    return content

tools_list = [read_markdown, write_content, write_paragraph, write_bullet_points,
              write_ordered_list, write_table, save_doc]
llm = llm.bind_tools(tools_list)

class AgentState(TypedDict):
    messages: Annotated[
        Sequence[BaseMessage], add_messages
    ]

def model_call(state: AgentState) -> AgentState:
    sys_msg = SystemMessage(content="""
        You are a helpful assistant!
        You are supposed to build a word document by reading instructions generated by another LLM agent.
        You and the other agent will receive the same user prompt

        You have seven tools: read_markdown, write_content, write_paragraph, write_bullet_points, write_ordered_list, write_table, save_doc
            read_markdown: call this tool to read the instructions
            write_content: to write the content.
            write_paragraph: write only paragraph to the document
            write_bullet_points: add bullet points in the document
            write_ordered_list: add order points in the document
            save_doc: save the doc
        Never call any other tool.
        Read the instructions, generate content and call the appropriate tool

        Do not search the web for any data, just answer with your knowledge.

        You are expected to create a word doc
    """)
    response = llm.invoke(
        [sys_msg] + state["messages"]
    )
    return dict(
        messages=[response]
    )

def should_continue(state: AgentState) -> str:
    messages = state["messages"][-1]
    if isinstance(messages, AIMessage) and messages.tool_calls:
        return "tool_node"

    return "stop"

graph = StateGraph(AgentState)

graph.add_node("model_call", model_call)
tool_node = ToolNode(tools = tools_list)
graph.add_node("tool_node", tool_node)

graph.add_edge(START, "model_call")
graph.add_conditional_edges("model_call",
                            should_continue,
                            {
                                "tool_node": "tool_node",
                                "stop": END
                            })
graph.add_edge("tool_node", "model_call")

app = graph.compile()

while True:
    user_input = input("Enter: ")
    if user_input.strip() == "q":
        break

    try:
        app.invoke(dict(
            messages=[("user", user_input)]
        ))
        print("Word generated!")
    except Exception as err:
        print(f"[ERR]: {str(err)}")