from typing import Union, List, Annotated, Sequence, TypedDict, Tuple
from dotenv import load_dotenv
import os

from langchain_groq import ChatGroq
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage, BaseMessage, SystemMessage, AIMessage
from langgraph.graph.message import add_messages
from langgraph.graph import StateGraph, START, END
from langgraph.prebuilt import ToolNode

from docx import Document
from docx.shared import Pt

from utils import *

load_dotenv()
API_KEY = os.getenv("GROQ_API_KEY")

llm = ChatGroq(
    model = "llama-3.1-8b-instant",
    api_key = API_KEY,
    temperature = 0
)

GLOBAL_DOC = Document()
DOC_PATH = os.path.join("generated","demo.docx")

@tool
def write_markdown(content: str) -> None:
    """
    Writes LLM generated todo list content in a md file
    :param content:
    :return:
    """
    with open("TODO.md", "w") as md:
        md.write(content)

@tool
def write_paragraph(para: str) -> str:
    """
    writes paragraph in the doc
    :param para: paragraph
    :return: confirmation
    """
    global GLOBAL_DOC
    GLOBAL_DOC.add_paragraph(para)
    return "paragraph added!"

@tool
def write_header(header: str) -> str:
    """
    writes header in the doc
    :param header: header
    :return: confirmation
    """
    global GLOBAL_DOC
    p = GLOBAL_DOC.add_paragraph()
    run = p.add_run(header)
    run.font.size = Pt(14)
    run.bold = True
    return "header added!"

@tool
def write_sub_header(sub_header: str) -> str:
    """
    writes sub_header in the doc
    :param sub_header: sub header
    :return: confirmation
    """
    global GLOBAL_DOC
    p = GLOBAL_DOC.add_paragraph()
    run = p.add_run(sub_header)
    run.font.size = Pt(12)
    run.bold = True
    return "header added!"

@tool
def write_bullet_points(points: List[str]) -> str:
    """
    writes bullet points in the doc
    :param points: bullet points
    :return: confirmation
    """
    global GLOBAL_DOC
    for p in points:
        GLOBAL_DOC.add_paragraph(p, style = "List Bullet")
    return "bullet points added!"

@tool
def write_ordered_list(points: List[str]) -> str:
    """
    writes ordered list in the doc
    :param points: ordered list
    :return: confirmation
    """
    global GLOBAL_DOC
    for p in points:
        GLOBAL_DOC.add_paragraph(p, style="List Number")
    return "bullet points added!"

@tool
def save_doc() -> str:
    """
    Saves the document
    :return: confirmation
    """
    global GLOBAL_DOC
    GLOBAL_DOC.save(DOC_PATH)
    return "Doc saved!"

@tool
def read_markdown() -> str:
    """
    Read instructions from a markdown file
    :return: instructions
    """
    with open("TODO.md", "r") as md:
        content = md.read()
    return content

tools_list = [write_markdown, read_markdown,
              write_paragraph, write_header, write_sub_header, write_bullet_points,write_ordered_list, save_doc]
llm = llm.bind_tools(tools_list)

class AgentState(TypedDict):
    messages: Annotated[
        Sequence[BaseMessage], add_messages
    ]

def create_todo(state: AgentState) -> AgentState:
    """
    Calls the LLM to generate a todo list
    :param state: AgentState
    :return: AgentState
    """
    example_prompt, example_response = get_sample_prompt_response()
    sys_msg = SystemMessage(content = f"""
        You are a helpful assistant!
        You are supposed to create a todo plan for another LLM agent to follow and create a word doc based on the user prompt.
        You and the other agent will receive the same user prompt

        You have one tool: write_markdown
        Never call any other tool

        example prompt: {example_prompt}
        example response: {example_response}

        Do not search the web for any data, just answer with your knowledge.
        Do not write the content for the word doc. Just refer the example prompt-response pair
    """)
    response = llm.invoke(
        [sys_msg] + state["messages"]
    )
    print("TODO created!")
    return dict(
        messages = [response]
    )

def generate_doc(state: AgentState) -> AgentState:
    """
    Generates content and calls tools to write content in the doc
    :param state: AgentState
    :return: AgentState
    """
    sys_msg = SystemMessage(content="""
        You are a helpful assistant!
        You are supposed to build a word document by reading instructions generated by another LLM agent.
        You and the other agent will receive the same user prompt

        You have these tools: 
            read_markdown: call this tool to read the instructions
            write_paragraph: write only paragraph to the document
            write_header: add a header in the document
            write_sub_header: adds a sub header (use this for the sub sections)
            write_bullet_points: add bullet points in the document
            write_ordered_list: add order points in the document
            save_doc: save the doc
        Never call any other tool.
        Read the instructions, generate content and call the appropriate tool

        Do not search the web for any data, just answer with your knowledge.

        You are expected to create a word doc
    """)
    response = llm.invoke(
        [sys_msg] + state["messages"]
    )
    # print(response.tool_calls)
    return dict(
        messages=[response]
    )

def should_continue(state: AgentState) -> str:
    messages = state["messages"][-1]
    if isinstance(messages, AIMessage) and messages.tool_calls:
        return "tool_node"
    return "stop"

graph = StateGraph(AgentState)

graph.add_node("create_todo", create_todo)
graph.add_node("generate_doc", generate_doc)
tool_node = ToolNode(tools = tools_list)
graph.add_node("tool_node", tool_node)

graph.add_edge(START, "create_todo")
graph.add_edge("create_todo", "tool_node")
graph.add_edge("tool_node","generate_doc")
graph.add_conditional_edges("generate_doc",
                            should_continue,
                            {
                                "tool_node": "tool_node",
                                "stop": END
                            })
graph.add_edge("tool_node", "generate_doc")

app = graph.compile()

prompts = {
    1: """We are planning an Agentic AI project that builds word documents based on plain human prompts. The app will take user prompt, this prompt will be sent to LLMs that will generate the task (for subsequent LLM) and finally create the word doc. Please help us create a word doc for this.""",

    2: """Generate meeting minutes for a weekly software development team meeting discussing sprint progress, completed tasks, blockers, action items, and deadlines.""",

    3: """We are planning to build a Smart Inventory Management System for retail stores. Create a professional project proposal that includes an executive summary, project objectives, key features, technology stack, implementation timeline, expected benefits, and conclusion.""",

    4: """Prepare a research report on the impact of Artificial Intelligence in healthcare. Include an introduction, literature review, major applications, benefits, challenges, future trends, and references."""
}

user_input = prompts[2]

try:
    app.invoke(dict(
        messages=[("user", user_input)]
    ))
    print("TODO generated!")
except Exception as err:
    print(f"[ERR]: {str(err)}")